export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR   = 'REGISTER_ERROR';
export const REGISTER_CLEAR   = 'REGISTER_CLEAR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR   = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR   = 'LOGOUT_ERROR';

export const SHOW_TOAST = 'SHOW_TOAST';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_ERROR   = 'PRODUCT_ERROR';

export const VIEW_PRODUCT_REQUEST = 'VIEW_PRODUCT_REQUEST';
export const VIEW_PRODUCT_SUCCESS = 'VIEW_PRODUCT_SUCCESS';
export const VIEW_PRODUCT_ERROR   = 'VIEW_PRODUCT_ERROR';

export const CAT_PRODUCT_REQUEST = 'CAT_PRODUCT_REQUEST';
export const CAT_PRODUCT_SUCCESS = 'CAT_PRODUCT_SUCCESS';
export const CAT_PRODUCT_ERROR   = 'CAT_PRODUCT_ERROR';

export const VIEW_CART_REQUEST = 'VIEW_CART_REQUEST';
export const VIEW_CART_SUCCESS = 'VIEW_CART_SUCCESS';
export const VIEW_CART_ERROR   = 'VIEW_CART_ERROR';

export const DELETE_CART_REQUEST = 'DELETE_CART_REQUEST';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_ERROR   = 'DELETE_CART_ERROR';

export const PAYMENT_CARD_REQUEST = 'PAYMENT_CARD_REQUEST';
export const PAYMENT_CARD_SUCCESS = 'PAYMENT_CARD_SUCCESS';
export const PAYMENT_CARD_ERROR   = 'PAYMENT_CARD_ERROR';

export const CART_PRODUCT_REQUEST = 'CART_PRODUCT_REQUEST';
export const CART_PRODUCT_SUCCESS = 'CART_PRODUCT_SUCCESS';
export const CART_PRODUCT_ERROR   = 'CART_PRODUCT_ERROR';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR   = 'ADD_PRODUCT_ERROR';

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST';
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS';
export const LIST_MY_ORDERS_ERROR   = 'LIST_MY_ORDERS_ERROR';